Repository codeit-bootcamp-frontend/10-Sprint-Mission, pull requests merged in 2024-10, with the labels that each got.

#100 [이수지] sprint7
  eslint.config.js
  src/App.css
  src/App.jsx
  src/api/index.js
  src/components/BestItem.jsx
  src/components/BestItem.module.css
  src/components/Card.jsx
  src/components/Card.module.css
  src/components/Container.jsx
  src/components/Container.module.css
  src/components/Nav.jsx
  src/components/Nav.module.css
  src/main.jsx
  src/pages/AddItemPage.jsx
  src/pages/HomePage.jsx
  src/pages/HomePage.module.css
  src/pages/ItemListPage.jsx
  src/pages/ItemListPage.module.css
  src/pages/ProductListPage.jsx
  src/pages/ProductPage.jsx
Labels: 매운맛🔥, 미완성🫠

#116 [정성현] sprint8
  .gitignore
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/_redirects
  src/Router.tsx
  src/apis/apis.js
  src/apis/apis.ts
  src/apis/apis.type.ts
  src/components/Dropdown.tsx
  src/components/PaginationBar.tsx
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/hooks/useApi.js
  src/hooks/useApi.ts
  src/hooks/useMediaQuery.ts
  src/index.js
  src/main.tsx
  src/pages/addItemPage/AddItemFormSection.tsx
  src/pages/addItemPage/AddItemPage.tsx
  src/pages/itemListPage/AllItemListSection.tsx
  src/pages/itemListPage/BestItemListSection.tsx
  src/pages/itemListPage/ItemListPage.tsx
  src/pages/itemListPage/components/Item.tsx
  src/pages/itemListPage/components/ItemListHead.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
Labels: 매운맛🔥, 미완성🫠

#110 [김창희] sprint8
  global.d.ts
  jsconfig.json
  package-lock.json
  package.json
  src/App.jsx
  src/App.tsx
  src/api/fetchData.ts
  src/components/Header.tsx
  src/components/Home.tsx
  src/components/additem/AddProduct.jsx
  src/components/additem/AddProduct.tsx
  src/components/additem/AddProductImage.jsx
  src/components/additem/AddProductImage.tsx
  src/components/additem/AddProductTag.jsx
  src/components/additem/AddProductTag.tsx
  src/components/additem/ProductDescription.jsx
  src/components/additem/ProductDescription.tsx
  src/components/additem/ProductPrice.tsx
  src/components/additem/ProductTagList.tsx
  src/components/additem/ProductTitle.jsx
  src/components/additem/ProductTitle.tsx
  src/components/additem/useAddItemSharedData.js
  src/components/additem/useAddItemSharedData.ts
  src/components/items/AllProductsHeader.tsx
  src/components/items/BestProductsHeader.tsx
  src/components/items/ItemPageNation.jsx
  src/components/items/ItemPageNation.tsx
  src/components/items/ProductCard.tsx
  src/components/items/productId/BackButton.tsx
  src/components/items/productId/Inquire.tsx
  src/components/items/productId/InquireItem.tsx
  src/components/items/productId/Line.jsx
  src/components/items/productId/Line.tsx
  src/components/items/productId/ProductImage.tsx
  src/components/items/productId/ProductSummary.tsx
  src/components/items/productId/useProductIdState.js
  src/components/items/productId/useProductIdState.ts
  src/components/items/useItemsSharedData.js
  src/components/items/useItemsSharedData.ts
  src/config/api.ts
  src/index.tsx
  src/pages/additem/AddItem.tsx
  src/pages/items/Items.tsx
  src/pages/items/productId/ProductId.tsx
  tsconfig.json
Labels: 매운맛🔥, 미완성🫠

#113 [김가희] sprint6
  package-lock.json
  package.json
  src/api.js
  src/components/App.js
  src/components/addItem/ItemInfo.js
  src/components/addItem/ItemName.js
  src/components/addItem/UploadImage.js
  src/components/addItem/UploadItem.js
  src/components/itemList/BestList.js
  src/components/itemList/BestList.module.css
  src/components/itemList/Card.js
  src/components/itemList/Card.module.css
  src/components/itemList/Favorite.js
  src/components/itemList/Favorite.module.css
  src/components/itemList/ItemList.js
  src/components/itemList/ItemList.module.css
  src/components/itemList/SearchBar.js
  src/components/itemList/SearchBar.module.css
  src/main.js
  src/pages/AddItemPage.js
  src/pages/ItemPage.js
Labels: 미완성🫠

#112 [김수영] sprint8
  .bash_profile
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.tsx
  src/Router.tsx
  src/api/itemApi.js
  src/api/itemApi.tsx
  src/components/Header/Header.tsx
  src/global.d.ts
  src/index.jsx
  src/pages/AddItem/AddItem.jsx
  src/pages/AddItem/AddItem.tsx
  src/pages/AddItem/components/ProductDescription/ProductDescription.tsx
  src/pages/AddItem/components/ProductImg/ProductImg.jsx
  src/pages/AddItem/components/ProductImg/ProductImg.tsx
  src/pages/AddItem/components/ProductName/ProductName.tsx
  src/pages/AddItem/components/ProductPrice/ProductPrice.tsx
  src/pages/AddItem/components/ProductTag/ProductTag.jsx
  src/pages/AddItem/components/ProductTag/ProductTag.tsx
  src/pages/Market/Market.tsx
  src/pages/Market/components/AllItem.jsx
  src/pages/Market/components/AllItem.tsx
  src/pages/Market/components/BestItem.tsx
  src/pages/Market/components/ItemCard.tsx
  src/pages/ProductDetail/ProductDetail.tsx
  src/pages/ProductDetail/components/Comment/Comment.jsx
  src/pages/ProductDetail/components/Comment/Comment.tsx
  src/pages/ProductDetail/components/CommentItem/CommentItem.tsx
  src/pages/ProductDetail/components/ProductInfo/ProductInfo.jsx
  src/pages/ProductDetail/components/ProductInfo/ProductInfo.tsx
  tsconfig.json
Labels: 매운맛🔥

#122 [나지원] sprint9
  .gitignore
  components/boards/ArticleImage.module.css
  components/boards/ArticleImage.tsx
  components/boards/BestBoard.module.css
  components/boards/BestBoard.tsx
  components/boards/BestBoards.module.css
  components/boards/BestBoards.tsx
  components/boards/Board.module.css
  components/boards/Board.tsx
  components/boards/BoardLIst.module.css
  components/boards/BoardList.tsx
  components/layout/Container.module.css
  components/layout/Container.tsx
  components/layout/Header.module.css
  components/layout/Header.tsx
  components/ui/AuthorInfo.module.css
  components/ui/AuthorInfo.tsx
  components/ui/Badge.module.css
  components/ui/Badge.tsx
  components/ui/Button.module.css
  components/ui/Button.tsx
  components/ui/Dropdown.module.css
  components/ui/Dropdown.tsx
  components/ui/LikeCount.module.css
  components/ui/LikeCount.tsx
  components/ui/SearchBar.module.css
  components/ui/SearchBar.tsx
  hooks/useResize.ts
  lib/fetchData.ts
  lib/formatDate.ts
  lib/urlParams.ts
  next-env.d.ts
  next.config.js
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/boards.tsx
  pages/index.tsx
  public/favicon.ico
  public/ic_arrow_down.svg
  public/ic_heart.svg
  public/ic_medal.svg
  public/ic_profile.svg
  public/ic_search.svg
  public/ic_sort.svg
  public/img_default.svg
  public/next.svg
  public/panda_logo.svg
  public/panda_typo.svg
  public/vercel.svg
  styles/Home.module.css
  styles/globals.css
  styles/reset.css
  styles/variables.css
  types/articleTypes.ts
Labels: 매운맛🔥

#117 [김희진] sprint9
  next.config.js
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/boards/components/BestBoardCard.module.css
  pages/boards/components/BestBoardCard.tsx
  pages/boards/components/BestBoards.module.css
  pages/boards/components/BestBoards.tsx
  pages/boards/components/Boards.module.css
  pages/boards/components/Boards.tsx
  pages/boards/index.tsx
  pages/index.tsx
  public/next.svg
  public/vercel.svg
  src/apis/boardTypes.ts
  src/apis/boardsApi.ts
  src/assets/avatar.svg
  src/assets/ic_heart.svg
  src/assets/ic_medal.svg
  src/assets/ic_search.svg
  src/assets/logo_lg.png
  src/assets/logo_sm.png
  src/components/Button.module.css
  src/components/Button.tsx
  src/components/GlobalLayout.module.css
  src/components/GlobalLayout.tsx
  src/components/Header.module.css
  src/components/Header.tsx
  styles/Home.module.css
  styles/globals.css
  styles/reset.css
Labels: 매운맛🔥, 미완성🫠

#121 [김태훈] sprint9
  components/ArticlesList.module.css
  components/ArticlesList.tsx
  components/BestArticles.module.css
  components/BestArticles.tsx
  components/CreateArticleButton.module.css
  components/CreateArticleButton.tsx
  components/Dropdown.module.css
  components/Dropdown.tsx
  components/Layout/Header.module.css
  components/Layout/Header.tsx
  components/SearchForm.module.css
  components/SearchForm.tsx
  lib/axios.js
  next.config.ts
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/boards/Board.module.css
  pages/boards/index.tsx
  pages/index.tsx
  public/images/home/bottom-banner-image.png
  public/images/home/feature1-image.png
  public/images/home/feature2-image.png
  public/images/home/feature3-image.png
  public/images/home/hero-image.png
  public/images/icons/arrow_left.svg
  public/images/icons/arrow_right.svg
  public/images/icons/eye-invisible.svg
  public/images/icons/eye-visible.svg
  public/images/icons/ic_back.svg
  public/images/icons/ic_heart.svg
  public/images/icons/ic_kebab.svg
  public/images/icons/ic_plus.svg
  public/images/icons/ic_search.svg
  public/images/icons/ic_sort.svg
  public/images/icons/ic_x.svg
  public/images/logo/logo.svg
  public/images/social/facebook-logo.svg
  public/images/social/google-logo.png
  public/images/social/instagram-logo.svg
  public/images/social/kakao-logo.png
  public/images/social/twitter-logo.svg
  public/images/social/youtube-logo.svg
  public/images/ui/best_badge.svg
  public/images/ui/empty-comments.svg
  public/images/ui/ic_profile.svg
  styles/CommonStyles.module.css
  styles/CommonStyles.ts
  styles/GlobalStyle.ts
  styles/Home.module.css
  styles/Theme.ts
  styles/globals.css
Labels: 순한맛🐑

#118 [김수영] sprint9
  .babelrc
  .bash_profile
  .github/workflows/delete-merged-branch-config.yml
  components/_styled/boardStyled.tsx
  components/_styled/mainStyled.tsx
  components/boards/BestPost.tsx
  components/boards/BestPostCard.tsx
  components/boards/PostCard.tsx
  components/boards/PostList.tsx
  components/boards/Styled.tsx
  components/common/function/elapsedTime.tsx
  components/common/function/formatDate.tsx
  components/common/images/default.png
  components/common/images/ic_heart.png
  components/common/images/ic_medal.png
  components/common/images/pandalogo.png
  components/common/images/postimg.png
  components/common/images/profile.png
  components/layout/Header.tsx
  components/layout/Layout.tsx
  components/layout/Styled.tsx
  global.d.ts
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/_document.tsx
  pages/api/api.tsx
  pages/api/hello.ts
  pages/boards/index.tsx
  pages/index.tsx
  public/PretendardVariable.woff2
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  styles/Home.module.css
  styles/globals.css
Labels: 매운맛🔥

#123 [정성현] sprint9
  README.md
  next.config.js
  pages/_app.tsx
  pages/_document.tsx
  pages/api/hello.ts
  pages/index.tsx
  public/favicon.ico
  public/fonts/PretendardVariable.woff2
  public/icons/heart_inactive.svg
  public/images/logo_w153x3.png
  public/images/profile_image_w40x3.png
  public/meta/favicon.ico
  public/meta/opengraph_image.png
  public/meta/twitter_image.png
  public/next.svg
  public/readme_banner.png
  public/vercel.svg
  src/apis/apis.ts
  src/apis/apis.type.ts
  src/components/layout/Header.module.css
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/pages/boards/BestItems.module.css
  src/components/pages/boards/BestItems.tsx
  src/components/pages/boards/componnets/BestItem.module.css
  src/components/pages/boards/componnets/BestItem.tsx
  src/hooks/useMediaQuery.ts
  src/hooks/useQuery.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/boards.module.css
  src/pages/boards.tsx
  src/pages/index.tsx
  src/pages/items.tsx
  src/styles/global.css
  src/styles/reset.css
  src/styles/variable.css
  styles/Home.module.css
  styles/globals.css
  tsconfig.json
Labels: 매운맛🔥, 미완성🫠

#120 [한수진] Sprint9
  .DS_Store
  .github/pull_request_template.md
  README.md
  components/ArticleList.js
  components/BehindList.js
  components/DropDown.js
  components/MoreButton.js
  components/SearchForm.js
  components/SizeReviewList.js
  image/ic_arrow_down.svg
  image/ic_heart.svg
  image/ic_medal.svg
  image/ic_profile.svg
  image/ic_search.svg
  image/logo.svg
  jsconfig.json
  lib/axios.js
  next.config.mjs
  package-lock.json
  package.json
  pages/_app.js
  pages/_document.js
  pages/boards/BehindBoard.js
  pages/boards/BestBoard.js
  pages/boards/[id].js
  pages/index.js
  pages/search.js
  pages/setting.js
  styles/ArticleList.module.css
  styles/BehindBoard.module.css
  styles/BehindList.module.css
  styles/BestBoard.module.css
  styles/DropDown.module.css
  styles/Home.module.css
  styles/Morebutton.module.css
  styles/Search.module.css
  styles/global.css
Labels: 미완성🫠, 순한맛🐑
