Repository codeit-bootcamp-frontend/10-Sprint-Mission, pull requests merged in 2024-09, with the labels that each got.

#59 [김수영] Sprint4
  .github/workflows/delete-merged-branch-config.yml
  img/btn_visibility_on.png
  index.html
  login.html
  script/auth.js
  signup.html
  style/auth.css
  style/auth_mobile.css
  style/global.css
  style/index.css
  style/index_mobile.css
  style/index_tablet.css
Labels: 매운맛🔥

#65 [김가희] sprint4
  login.css
  login.html
  login.js
  signup.html
  signup.js
Labels: 순한맛🐑

#63 [김태훈] sprint4
  FAQ/index.html
  images/Component 2@3x.png
  images/Component 3@3x.png
  images/Img_home_01.png
  images/Img_home_01@2x.png
  images/Img_home_01@3x.png
  images/Img_home_02-1.png
  images/Img_home_02.png
  images/Img_home_02@2x.png
  images/Img_home_03.png
  images/Img_home_03@2x.png
  images/Img_home_03@3x.png
  images/Img_home_bottom.png
  images/Img_home_bottom@2x.png
  images/Img_home_bottom@3x.png
  images/Img_home_top.png
  images/Img_home_top@2x.png
  images/Img_home_top@3x.png
  images/Property 1=lg@3x.png
  images/eye-invisible.svg
  images/eye-visible.svg
  images/ic_facebook@3x.png
  images/ic_instagram@3x.png
  images/ic_twitter@3x.png
  images/ic_youtube@3x.png
  images/logo/logo.svg
  images/panda_logo_1_2x.png
  index.html
  index.js
  login/index.html
  login/index.js
  privacy/index.html
  signup/index.html
  signup/index.js
  styles/home.css
  styles/login-signup.css
Labels: 매운맛🔥

#58 [김희진] sprint4
  css/global.css
  css/home.css
  css/login.css
  images/btn_visibility_off.svg
  images/btn_visibility_on.svg
  images/ic_facebook.png
  images/ic_facebook.svg
  images/ic_google.png
  images/ic_google.svg
  images/ic_instagram.png
  images/ic_instagram.svg
  images/ic_kakaotalk.png
  images/ic_kakaotalk.svg
  images/ic_twitter.png
  images/ic_twitter.svg
  images/ic_youtube.png
  images/ic_youtube.svg
  index.html
  items/index.html
  login/index.html
  signup/index.html
  src/login.js
  src/signup.js
  src/validationConstants.js
  src/validationErrorMessage.js
Labels: 매운맛🔥

#70 [김지윤]sprint4
  auth-validation.js
  css/components/footer.css
  css/responsive/auth-res.css
  css/responsive/footer-res.css
  css/responsive/header-res.css
  css/responsive/landing-res.css
  css/screens/auth.css
  css/screens/landing.css
  css/styles.css
  css/variables.css
  images/icon/pw-hidden.png
  images/icon/pw-view.png
  index.html
  items.html
  login.html
  signup.html
  toggle-pw.js
Labels: 미완성🫠

#71 [박지민] sprint4
  faq.html
  index.html
  items.html
  login.html
  node_modules/.package-lock.json
  node_modules/normalize.css/CHANGELOG.md
  node_modules/normalize.css/LICENSE.md
  node_modules/normalize.css/README.md
  node_modules/normalize.css/normalize.css
  node_modules/normalize.css/package.json
  package-lock.json
  package.json
  privacy.html
  signup.html
  src/login.js
  src/signup.js
  styles/login_signin.css
  styles/style.css
  styles/style_mobile.css
  styles/style_tablet.css
Labels: 미완성🫠

#68 [한수진]sprint4
  .DS_Store
  .github/.gitignore
  JavaScript/inscript.js
  JavaScript/upscript.js
  images/.DS_Store
  signin.html
  signup.html
  styles/.DS_Store
  styles/sign.css
  styles/signin.css
  styles/style.css
Labels: 순한맛🐑

#61 [나지원] sprint4
  README.md
  css/auth.css
  css/main.css
  css/reset.css
  css/variables.css
  images/btn_hide.svg
  images/btn_show.svg
  index.html
  login.html
  signup.html
  src/auth.js
  src/login.js
  src/signup.js
Labels: 매운맛🔥

#64 [나승엽] sprint4
  index.html
  login.html
  sign_up.html
  로그인&회원가입.css
  로그인&회원가입.js
  로그인&회원가입반응형.css
  반응형디자인적용.css
Labels: 매운맛🔥

#62 [이수지] sprint4
  css/auth.css
  css/main.css
  index.html
  pages/login.html
  pages/signup.html
  scripts/login.js
Labels: 매운맛🔥, 미완성🫠

#76 [고태호] Sprint 5
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/logo.png
  public/profile.png
  src/App.css
  src/App.jsx
  src/assets/Icon.png
  src/assets/Polygon.png
  src/assets/Vector.png
  src/component/BestProducts.jsx
  src/component/Header.jsx
  src/component/Pagination.jsx
  src/component/ProductList.jsx
  src/component/SortMenu.jsx
  src/index.css
  src/main.jsx
  vite.config.js
Labels: 매운맛🔥

#77 [김수영] sprint5
  package-lock.json
  package.json
  src/App.js
  src/App.test.js
  src/Router.jsx
  src/api/itemApi.js
  src/assets/images/itemimg.png
  src/assets/images/likeicon.png
  src/assets/images/pandalogo.png
  src/assets/images/profile.png
  src/assets/images/searchicon.png
  src/components/Header/Header.css
  src/components/Header/Header.jsx
  src/index.js
  src/logo.svg
  src/pages/Market/Market.css
  src/pages/Market/Market.jsx
  src/pages/Market/components/AllItem.jsx
  src/pages/Market/components/BestItem.jsx
  src/pages/Market/components/ItemCard.jsx
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/global.css
Labels: 매운맛🔥

#79 [한수진]sprint5
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/.DS_Store
  src/App.css
  src/App.js
  src/App.test.js
  src/assets/.DS_Store
  src/assets/images/.DS_Store
  src/assets/images/home/bottom-banner-image.png
  src/assets/images/home/feature1-image.png
  src/assets/images/home/feature2-image.png
  src/assets/images/home/feature3-image.png
  src/assets/images/home/hero-image.png
  src/assets/images/icons/.DS_Store
  src/assets/images/icons/arrow_left.svg
  src/assets/images/icons/arrow_right.svg
  src/assets/images/icons/ic_heart.svg
  src/assets/images/icons/ic_profile.svg
  src/assets/images/icons/ic_search.svg
  src/assets/images/icons/ic_sort.svg
  src/assets/images/logo/logo.svg
  src/assets/images/logo/panda-image.png
  src/assets/images/social/facebook-logo.svg
  src/assets/images/social/google-logo.png
  src/assets/images/social/instagram-logo.svg
  src/assets/images/social/kakao-logo.png
  src/assets/images/social/twitter-logo.svg
  src/assets/images/social/youtube-logo.svg
  src/components/App.js
  src/components/pages/Header.css
  src/components/pages/Header.jsx
  src/components/pages/junggo/AllProducts.js
  src/components/pages/junggo/BestProducts.jsx
  src/components/pages/junggo/ItemCard.css
  src/components/pages/junggo/ItemCard.jsx
  src/components/pages/junggo/global.css
  src/components/pages/mainpage/main.html
  src/components/pages/mainpage/style.css
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/services/itemApi.jsx
  src/setupTests.js
Labels: 미완성🫠, 순한맛🐑

#82 [정성현] sprint5
  README.md
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/opengraph_w1200.png
  public/robots.txt
  readme/banner_w1440.png
  src/App.css
  src/App.js
  src/App.test.js
  src/apis/.gitkeep
  src/assets/.gitkeep
  src/components/.gitkeep
  src/constants/.gitkeep
  src/contexts/.gitkeep
  src/hooks/.gitkeep
  src/index.css
  src/index.js
  src/logo.svg
  src/pages/.gitkeep
  src/reportWebVitals.js
  src/setupTests.js
  src/styles/global.css
  src/styles/reset.css
  src/styles/variable.css
  src/utils/.gitkeep
Labels: 매운맛🔥, 미완성🫠

#92 [김가희] sprint6
  package-lock.json
  package.json
  public/Pretendard-Regular.ttf
  public/favicon.ico
  public/images/free-icon-no-pictures-3875148.png
  public/images/heart-icon.svg
  public/images/panda-logo.svg
  public/images/user-icon.svg
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/api.js
  src/components/App.js
  src/components/BestList.js
  src/components/BestList.module.css
  src/components/Card.js
  src/components/Card.module.css
  src/components/Favorite.js
  src/components/Favorite.module.css
  src/components/ItemList.js
  src/components/ItemList.module.css
  src/components/Nav.js
  src/components/Nav.module.css
  src/components/SearchBar.js
  src/components/SearchBar.module.css
  src/index.css
  src/index.js
  src/logo.svg
  src/main.js
  src/pages/ItemPage.js
  src/reportWebVitals.js
  src/setupTests.js
Labels: 미완성🫠

#91 [김수영] sprint6
  .github/workflows/delete-merged-branch-config.yml
  src/Router.jsx
  src/api/itemApi.js
  src/assets/images/plusicon.png
  src/assets/images/xicon.png
  src/components/Header/Header.jsx
  src/pages/AddItem/AddItem.css
  src/pages/AddItem/AddItem.jsx
  src/pages/AddItem/components/ProductDescription/ProductDescription.css
  src/pages/AddItem/components/ProductDescription/ProductDescription.jsx
  src/pages/AddItem/components/ProductImg/ProductImg.css
  src/pages/AddItem/components/ProductImg/ProductImg.jsx
  src/pages/AddItem/components/ProductName/ProductName.css
  src/pages/AddItem/components/ProductName/ProductName.jsx
  src/pages/AddItem/components/ProductPrice/ProductPrice.css
  src/pages/AddItem/components/ProductPrice/ProductPrice.jsx
  src/pages/AddItem/components/ProductTag/ProductTag.css
  src/pages/AddItem/components/ProductTag/ProductTag.jsx
  src/pages/Market/components/AllItem.jsx
  src/pages/Market/components/ItemCard.jsx
  src/styles/global.css
Labels: 매운맛🔥

#93 [정성현] sprint6
  package-lock.json
  package.json
  src/App.js
  src/Router.js
  src/apis/.gitkeep
  src/apis/apis.js
  src/assets/.gitkeep
  src/assets/arrow_down.svg
  src/assets/arrow_left_active.svg
  src/assets/arrow_left_inactive.svg
  src/assets/arrow_right_active.svg
  src/assets/arrow_right_inactive.svg
  src/assets/heart_active.svg
  src/assets/heart_inactive.svg
  src/assets/logo_w153x3.png
  src/assets/logo_w81x3.png
  src/assets/profile_image_w40x3.png
  src/assets/search.svg
  src/assets/sort.svg
  src/components/.gitkeep
  src/components/Dropdown.css
  src/components/Dropdown.js
  src/components/PagenationBar.css
  src/components/PagenationBar.js
  src/components/layout/Layout.css
  src/components/layout/Layout.js
  src/hooks/.gitkeep
  src/hooks/useApi.js
  src/hooks/useMediaQuery.js
  src/index.js
  src/pages/.gitkeep
  src/pages/itemListPage/AllItemListSection.css
  src/pages/itemListPage/AllItemListSection.js
  src/pages/itemListPage/BestItemListSection.css
  src/pages/itemListPage/BestItemListSection.js
  src/pages/itemListPage/ItemListPage.css
  src/pages/itemListPage/ItemListPage.js
  src/pages/itemListPage/components/Item.css
  src/pages/itemListPage/components/Item.js
  src/pages/itemListPage/components/ItemListHead.css
  src/pages/itemListPage/components/ItemListHead.js
Labels: 매운맛🔥, 미완성🫠

#90 [고태호] Sprint6
  README.md
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/api.js
  src/component/BestProducts.jsx
  src/component/Header.jsx
  src/component/Pagination.jsx
  src/component/ProductList.jsx
  src/component/SortDropdown.jsx
  src/main.jsx
  src/page/MainContent.jsx
  src/page/additem.jsx
Labels: 매운맛🔥

#86 [이수지] sprint6
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.font.css
  src/App.js
  src/App.jsx
  src/App.module.css
  src/App.test.js
  src/api/index.js
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Bold.woff2
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-Medium.woff2
  src/assets/fonts/Pretendard-Regular.woff
  src/assets/fonts/Pretendard-Regular.woff2
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/Pretendard-SemiBold.woff2
  src/assets/images/ic-cancel.svg
  src/assets/images/ic-heart.svg
  src/assets/images/ic-plus.svg
  src/assets/images/ic-profile.svg
  src/assets/images/logo-sm.png
  src/components/BestItem.jsx
  src/components/BestItem.module.css
  src/components/Card.jsx
  src/components/Card.module.css
  src/components/Container.jsx
  src/components/Container.module.css
  src/components/Nav.jsx
  src/components/Nav.module.css
  src/index.css
  src/index.js
  src/logo.svg
  src/main.jsx
  src/pages/AddItemPage.jsx
  src/pages/HomePage.jsx
  src/pages/HomePage.module.css
  src/pages/ItemListPage.jsx
  src/pages/ItemListPage.module.css
  src/reportWebVitals.js
  src/setupTests.js
  vite.config.js
  yarn.lock
Labels: 매운맛🔥, 미완성🫠

#103 [김창희] sprint7
  src/App.jsx
  src/assets/imgs/ic_back.svg
  src/assets/imgs/ic_ellipsis.svg
  src/assets/imgs/no_inquire.svg
  src/components/items/ProductCard.jsx
  src/components/items/productId/BackButton.jsx
  src/components/items/productId/BackButton.module.css
  src/components/items/productId/Inquire.jsx
  src/components/items/productId/Inquire.module.css
  src/components/items/productId/InquireItem.jsx
  src/components/items/productId/InquireItem.module.css
  src/components/items/productId/Line.jsx
  src/components/items/productId/Line.module.css
  src/components/items/productId/ProductImage.jsx
  src/components/items/productId/ProductImage.module.css
  src/components/items/productId/ProductSummary.jsx
  src/components/items/productId/ProductSummary.module.css
  src/components/items/productId/useProductIdState.js
  src/config/api.js
  src/pages/items/Items.jsx
  src/pages/items/productId/ProductId.jsx
  src/pages/items/productId/ProductId.module.css
Labels: 매운맛🔥

#102 [나지원] sprint7
  src/assets/images/ic_back.svg
  src/assets/images/ic_kebab.svg
  src/assets/images/img_inquiry_empty.svg
  src/components/Button.js
  src/components/Button.module.css
  src/components/Card.js
  src/components/Card.module.css
  src/components/HeartButton.js
  src/components/HeartButton.module.css
  src/components/Input.js
  src/components/Tags.js
  src/components/Tags.module.css
  src/components/Textarea.js
  src/components/Textarea.module.css
  src/components/XButton.js
  src/components/XButton.module.css
  src/constants/api.js
  src/constants/message.js
  src/features/AddProduct/components/AddProductForm.js
  src/features/AddProduct/components/AddProductForm.module.css
  src/features/AddProduct/components/FileInput.js
  src/features/AddProduct/components/Tags.js
  src/features/Product/components/AuthorInfo.js
  src/features/Product/components/AuthorInfo.module.css
  src/features/Product/components/Comments.js
  src/features/Product/components/Comments.module.css
  src/features/Product/components/Dropdown.js
  src/features/Product/components/Dropdown.module.css
  src/features/Product/components/Inquiry.js
  src/features/Product/components/Inquiry.module.css
  src/features/Product/components/ProductDetail.js
  src/features/Product/components/ProductDetail.module.css
  src/features/Product/services/getProudct.js
  src/features/ProductList/components/Dropdown.js
  src/features/ProductList/components/Dropdown.module.css
  src/features/ProductList/services/getProducts.js
  src/pages/AddProductPage.js
  src/pages/ProductListPage.js
  src/pages/ProductPage.js
  src/pages/ProductPage.module.css
  src/routes/AppRoutes.js
  src/utils/commonUtils.js
Labels: 매운맛🔥

#101 고태호 [sprint 7]
  .gitignore
  Heart.png
  README.md
  dist/assets/index-B8re9kkF.js
  dist/assets/index-DLNfu7h6.css
  dist/index.html
  dist/logo.png
  package-lock.json
  package.json
  src/App.css
  src/App.jsx
  src/api.js
  src/assets/Heart.png
  src/assets/Registimg.png
  src/assets/commentPatchRmbtn.png
  src/assets/ic_back.png
  src/assets/profile.png
  src/component/DetailPage/Comment.jsx
  src/component/DetailPage/Inquiry.jsx
  src/component/DetailPage/ProductIntro.jsx
  src/component/MainContent/BestProducts.jsx
  src/component/MainContent/Header.jsx
  src/component/MainContent/Pagination.jsx
  src/component/MainContent/ProductList.jsx
  src/component/MainContent/SortDropdown.jsx
  src/component/additem/AdditemHeader.jsx
  src/component/additem/ItemImage.jsx
  src/component/additem/ItemIntro.jsx
  src/component/additem/ItemName.jsx
  src/component/additem/ItemPrice.jsx
  src/component/additem/ItemTag.jsx
  src/page/DetailPage.jsx
  src/page/MainContent.jsx
  src/page/additem.jsx
Labels: 매운맛🔥

#99 [김수영] sprint7
  src/Router.jsx
  src/api/itemApi.js
  src/assets/images/backicon.png
  src/assets/images/hearticon.png
  src/pages/AddItem/components/ProductDescription/ProductDescription.css
  src/pages/AddItem/components/ProductImg/ProductImg.jsx
  src/pages/AddItem/components/ProductTag/ProductTag.jsx
  src/pages/Market/Market.jsx
  src/pages/Market/Market.module.css
  src/pages/Market/components/AllItem.jsx
  src/pages/Market/components/BestItem.jsx
  src/pages/Market/components/ItemCard.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductDetail.module.css
  src/pages/ProductDetail/components/Comment/Comment.jsx
  src/pages/ProductDetail/components/Comment/Comment.module.css
  src/pages/ProductDetail/components/CommentItem/CommentItem.jsx
  src/pages/ProductDetail/components/CommentItem/CommentItem.module.css
  src/pages/ProductDetail/components/ProductInfo/ProductInfo.css
  src/pages/ProductDetail/components/ProductInfo/ProductInfo.jsx
Labels: 매운맛🔥

#97 React 김주동 sprint7
  .gitignore
  package-lock.json
  package.json
  package.json.bak
  public/index.html
  src/App.js
  src/api/itemApi.js
  src/assets/images/icons/ic_back.svg
  src/assets/images/icons/ic_kebab.svg
  src/assets/images/icons/ic_plus.svg
  src/assets/images/icons/ic_x.svg
  src/assets/images/ui/empty-comments.svg
  src/assets/images/ui/ic_profile.svg
  src/components/Layout/Header.css
  src/components/Layout/Header.jsx
  src/components/UI/DeleteButton.jsx
  src/components/UI/DropdownMenu.css
  src/components/UI/DropdownMenu.jsx
  src/components/UI/Icon.jsx
  src/components/UI/ImageUpload.jsx
  src/components/UI/InputItem.jsx
  src/components/UI/LoadingSpinner.jsx
  src/components/UI/PaginationBar.css
  src/components/UI/TagInput.jsx
  src/index.js
  src/pages/AddItemPage/AddItemPage.jsx
  src/pages/ItemPage/ItemPage.jsx
  src/pages/ItemPage/components/CommentThread.jsx
  src/pages/ItemPage/components/ItemCommentSection.jsx
  src/pages/ItemPage/components/ItemProfileSection.jsx
  src/pages/ItemPage/components/LikeButton.jsx
  src/pages/ItemPage/components/TagDisplay.jsx
  src/pages/MarketPage/MarketPage.css
  src/pages/MarketPage/components/AllItemsSection.jsx
  src/pages/MarketPage/components/BestItemsSection.jsx
  src/pages/MarketPage/components/ItemCard.jsx
  src/styles/CommonStyles.js
  src/styles/GlobalStyle.js
  src/styles/global.css
  src/styles/theme.js
  src/utils/dateUtils.js
Labels: 순한맛🐑

#104 [정성현] sprint7
  src/Router.js
  src/apis/apis.js
  src/components/Dropdown.css
  src/components/Dropdown.js
  src/components/PaginationBar.css
  src/components/PaginationBar.js
  src/components/layout/Header.css
  src/components/layout/Header.js
  src/components/layout/Layout.js
  src/hooks/useApi.js
  src/pages/addItemPage/AddItemFormSection.css
  src/pages/addItemPage/AddItemFormSection.js
  src/pages/addItemPage/AddItemPage.css
  src/pages/addItemPage/AddItemPage.js
  src/pages/itemListPage/AllItemListSection.js
  src/pages/itemListPage/BestItemListSection.js
  src/pages/itemListPage/components/Item.js
  src/pages/itemListPage/components/ItemListHead.js
  src/styles/reset.css
Labels: 매운맛🔥, 미완성🫠

#96 [김희진] sprint7
  src/App.js
  src/assets/enquiry_empty.svg
  src/assets/ic_return.svg
  src/components/PrimaryButton.jsx
  src/components/PrimaryRoundButton.css
  src/components/PrimaryRoundButton.jsx
  src/components/Textarea.css
  src/components/Textarea.jsx
  src/components/item/AllItems.jsx
  src/components/item/Comment.css
  src/components/item/Comment.jsx
  src/components/item/Comments.css
  src/components/item/Comments.jsx
  src/components/item/Enquiry.css
  src/components/item/Enquiry.jsx
  src/components/item/Favorite.css
  src/components/item/Favorite.jsx
  src/components/item/Item.jsx
  src/components/item/ItemDetails.css
  src/components/item/ItemDetails.jsx
  src/components/item/ItemForm.jsx
  src/components/item/SortDropdown.jsx
  src/components/item/TagCard.css
  src/components/item/TagCard.jsx
  src/components/item/pagination/Pagination.jsx
  src/components/item/pagination/PaginationButton.jsx
  src/pages/ItemDetailPage.css
  src/pages/ItemDetailPage.jsx
  src/services/itemApi.js
  src/utils/dateFormat.js
Labels: 매운맛🔥
