Repository codeit-bootcamp-frontend/10-Sprint-Mission, pull requests merged in 2024-08, with the labels that each got.

#1 [김가희] sprint1
  FAQ.html
  Group_22.png
  Img_home_bottom.png
  Img_home_top.png
  Pretendard-Regular.ttf
  ROKAF_Sans_Medium.ttf
  desktop_02.png
  desktop_03.png
  desktop_04.png
  facebook.png
  index.html
  instagram.png
  login.html
  lookaround.html
  privacy_policy.html
  style.css
  twitter.png
  youtube.png
Labels: 미완성🫠

#6 [김희진] sprint1
  css/global.css
  css/home.css
  faq.html
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/hero.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/logo.png
  index.html
  items.html
  login.html
  privacy.html
Labels: 매운맛🔥

#11 [김지윤] Sprint1
  css/components/footer.css
  css/components/header.css
  css/screens/landing-page.css
  css/styles.css
  css/variables.css
  faq.html
  images/footer/ic_facebook.png
  images/footer/ic_instagram.png
  images/footer/ic_twitter.png
  images/footer/ic_youtube.png
  images/header/Property 1=sm.png
  images/header/Property 1=sm@2x.png
  images/header/Property 1=sm@3x.png
  images/main/Img_home_01.png
  images/main/Img_home_02.png
  images/main/Img_home_03.png
  images/main/Img_home_bottom.png
  images/main/Img_home_top.png
  index.html
  items.html
  login.html
  privacy.html
Labels: 순한맛🐑

#7 [김수영] Sprint1
  .vscode/settings.json
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/icon/ic_facebook.png
  img/icon/ic_instagram.png
  img/icon/ic_twitter.png
  img/icon/ic_youtube.png
  img/logo/logo.png
  index.html
  style/style.css
Labels: 매운맛🔥

#4 [이수지] sprint1
  .vscode/settings.json
  assets/fonts/Pretendard-Black.woff
  assets/fonts/Pretendard-Black.woff2
  assets/fonts/Pretendard-Bold.woff
  assets/fonts/Pretendard-Bold.woff2
  assets/fonts/Pretendard-ExtraBold.woff
  assets/fonts/Pretendard-ExtraBold.woff2
  assets/fonts/Pretendard-ExtraLight.woff
  assets/fonts/Pretendard-ExtraLight.woff2
  assets/fonts/Pretendard-Light.woff
  assets/fonts/Pretendard-Light.woff2
  assets/fonts/Pretendard-Medium.woff
  assets/fonts/Pretendard-Medium.woff2
  assets/fonts/Pretendard-Regular.woff
  assets/fonts/Pretendard-Regular.woff2
  assets/fonts/Pretendard-SemiBold.woff
  assets/fonts/Pretendard-SemiBold.woff2
  assets/fonts/Pretendard-Thin.woff
  assets/fonts/Pretendard-Thin.woff2
  assets/images/Img_home_01.jpg
  assets/images/Img_home_02.jpg
  assets/images/Img_home_03.jpg
  assets/images/Img_home_bottom.png
  assets/images/Img_home_top.png
  assets/images/ic_facebook.svg
  assets/images/ic_instagram.svg
  assets/images/ic_twitter.svg
  assets/images/ic_youtube.svg
  assets/images/logo-sm.png
  css/fonts.css
  css/main.css
  index.html
Labels: 매운맛🔥

#14 [정성현] sprint1
  README.md
  faq.html
  images/explain_1.png
  images/explain_2.png
  images/explain_3.png
  images/facebook.png
  images/instagram.png
  images/logo_icon.png
  images/logo_lg.png
  images/logo_md.png
  images/logo_sm.png
  images/panda_1.png
  images/panda_2.png
  images/twitter.png
  images/youtube.png
  index.html
  init.css
  items.html
  login.html
  privacy.html
  style.css
Labels: 매운맛🔥

#18 [최순오]sprint 1
  10-Sprint-Mission/css/style.css
  10-Sprint-Mission/img/Img_home_bottom.png
  10-Sprint-Mission/img/Img_home_top.png
  10-Sprint-Mission/img/Rectangle 1123.png
  10-Sprint-Mission/img/btn/btn_small-1.png
  10-Sprint-Mission/img/btn/btn_small-2.png
  10-Sprint-Mission/img/btn/btn_small-3.png
  10-Sprint-Mission/img/btn/btn_small.png
  10-Sprint-Mission/img/btn/state=active.png
  10-Sprint-Mission/img/btn/state=click.png
  10-Sprint-Mission/img/btn/state=hover.png
  10-Sprint-Mission/img/btn/state=inactive.png
  10-Sprint-Mission/img/gnb/size=desktop, sort=Default.png
  10-Sprint-Mission/img/gnb/standard=pc.png
  10-Sprint-Mission/img/icons/Editor Icon.png
  10-Sprint-Mission/img/icons/arrow_left.png
  10-Sprint-Mission/img/icons/arrow_left/ic_back.png
  10-Sprint-Mission/img/icons/arrow_right.png
  10-Sprint-Mission/img/icons/btn_visibility_on_24px.png
  10-Sprint-Mission/img/icons/ic_X.png
  10-Sprint-Mission/img/icons/ic_arrow_down.png
  10-Sprint-Mission/img/icons/ic_check.png
  10-Sprint-Mission/img/icons/ic_facebook.png
  10-Sprint-Mission/img/icons/ic_heart.png
  10-Sprint-Mission/img/icons/ic_instagram.png
  10-Sprint-Mission/img/icons/ic_plus.png
  10-Sprint-Mission/img/icons/ic_profile.png
  10-Sprint-Mission/img/icons/ic_search.png
  10-Sprint-Mission/img/icons/ic_search_darker.png
  10-Sprint-Mission/img/icons/ic_sort.png
  10-Sprint-Mission/img/icons/ic_twitter.png
  10-Sprint-Mission/img/icons/ic_youtube.png
  10-Sprint-Mission/img/icons/img_badge.png
  10-Sprint-Mission/img/landing/desktop_01.png
  10-Sprint-Mission/img/landing/desktop_02.png
  10-Sprint-Mission/img/landing/desktop_03.png
  10-Sprint-Mission/img/landing/desktop_04.png
  10-Sprint-Mission/img/landing/desktop_05.png
  10-Sprint-Mission/img/landing/mobile_01.png
  10-Sprint-Mission/img/landing/mobile_02.png
  10-Sprint-Mission/img/landing/mobile_03.png
  10-Sprint-Mission/img/landing/mobile_04.png
  10-Sprint-Mission/img/landing/mobile_05.png
  10-Sprint-Mission/img/landing/tablet_01.png
  10-Sprint-Mission/img/landing/tablet_02.png
  10-Sprint-Mission/img/landing/tablet_03.png
  10-Sprint-Mission/img/landing/tablet_04.png
  10-Sprint-Mission/img/landing/tablet_05.png
  10-Sprint-Mission/img/lg/Property 1=Typo.png
  10-Sprint-Mission/img/lg/Property 1=lg.png
  10-Sprint-Mission/img/lg/Property 1=md.png
  10-Sprint-Mission/img/lg/Property 1=sm.png
  10-Sprint-Mission/img/main/Img_home_01.png
  10-Sprint-Mission/img/main/Img_home_02.png
  10-Sprint-Mission/img/main/Img_home_03.png
  10-Sprint-Mission/index.html
  10-Sprint-Mission/links/Privacy.html
  10-Sprint-Mission/links/faq.html
  10-Sprint-Mission/links/item.html
  10-Sprint-Mission/links/login.html
Labels: 매운맛🔥, 순한맛🐑

#16 [모수진]sprint1
  desktop.html
  image/Img_home_01.png
  image/Img_home_02.png
  image/Img_home_03.png
  image/Img_home_bottom.png
  image/Img_home_top.png
  image/ic_facebook.png
  image/ic_instagram.png
  image/ic_twitter.png
  image/ic_youtube.png
  image/lg.png
  image/md.png
  image/sm.png
  image/typo.png
  items.html
  login.html
  style_desktop.css
Labels: bug, 매운맛🔥

#3 [나지원] Sprint1
  .gitignore
  README.md
  css/main.css
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/panda_logo.png
  index.html
Labels: 매운맛🔥

#5 [고태호]Sprint1
  .github/pull_request_template.md
  faq.html
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/home/password_eye.png
  images/logo/Component 2.png
  images/logo/Component 3.png
  images/logo/favicon.ico
  images/logo/panda-market-logo.png
  images/social/facebook-logo.svg
  images/social/instagram-logo.svg
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  index.html
  items.html
  login.html
  privacy.html
  sign_in.html
  styles/global.css
  styles/home.css
Labels: 매운맛🔥

#28 [김수영] sprint2
  .gitignore
  img/btn_visibility_off.png
  img/icon/ic_google.png
  img/icon/ic_kakao.png
  index.html
  login.html
  signup.html
  style/auth.css
  style/global.css
  style/index.css
Labels: 매운맛🔥

#27 [이수지] sprint2
  .gitignore
  .vscode/settings.json
  assets/fonts/Pretendard-Black.woff
  assets/fonts/Pretendard-Black.woff2
  assets/fonts/Pretendard-ExtraBold.woff
  assets/fonts/Pretendard-ExtraBold.woff2
  assets/fonts/Pretendard-ExtraLight.woff
  assets/fonts/Pretendard-ExtraLight.woff2
  assets/fonts/Pretendard-Light.woff
  assets/fonts/Pretendard-Light.woff2
  assets/fonts/Pretendard-Thin.woff
  assets/fonts/Pretendard-Thin.woff2
  assets/images/btn-visibility-off.svg
  assets/images/btn-visibility-on.svg
  assets/images/ic-facebook.svg
  assets/images/ic-google.svg
  assets/images/ic-instagram.svg
  assets/images/ic-kakao.svg
  assets/images/ic-twitter.svg
  assets/images/ic-youtube.svg
  assets/images/img-home-01.jpg
  assets/images/img-home-02.jpg
  assets/images/img-home-03.jpg
  assets/images/img-home-bottom.png
  assets/images/img-home-top.png
  assets/images/logo-lg.png
  css/common.css
  css/fonts.css
  css/login.css
  css/main.css
  css/signup.css
  index.html
  pages/login.html
  pages/signup.html
Labels: 매운맛🔥

#34 [한수진]sprint2
  .DS_Store
  images/.DS_Store
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/google-logo.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/kakao-logo.png
  images/login1.png
  images/login2.png
  images/login3.png
  images/login4.png
  images/logopanda.png
  images/logopanda1.png
  images/logopanda2x.png
  images/logopanda3x.png
  images/logopandal2x.png
  images/logopandal3x.png
  images/logopandamd.png
  images/logopandas2x.png
  images/mobile_01.png
  images/mobile_02.png
  images/mobile_03.png
  images/mobile_04.png
  images/mobile_05.png
  images/namepanda1.png
  images/namepanda2.png
  images/namepanda3.png
  images/shopping.png
  index.html
  login.html
  signin.css
  signlink.css
  signup.html
  style.css
Labels: 순한맛🐑

#43 [박지민] sprint2
  assets/Img_home_01.png
  assets/Img_home_02.png
  assets/Img_home_03.png
  assets/Img_home_bottom.png
  assets/Img_home_top.png
  assets/btn_visibility_off_24px.png
  assets/btn_visibility_on_24px.png
  assets/ic_color_google.png
  assets/ic_color_kakaotalk.png
  assets/ic_facebook.png
  assets/ic_instagram.png
  assets/ic_twitter.png
  assets/ic_youtube.png
  assets/logo.png
  assets/logo_lg.png
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  style.css
Labels: 매운맛🔥

#10 [나승엽] Sprint2
  Group 22.png
  Img_home_01.png
  Img_home_02.png
  Img_home_03.png
  Img_home_bottom.png
  Img_home_top.png
  cacaotalk.png
  google.png
  ic_facebook (1).png
  ic_instagram.png
  ic_twitter.png
  ic_youtube.png
  index.html
  login.html
  reset.css
  sign_up.html
  로그인&회원가입.css
  스프린트미션.css
  판다 얼굴.png
Labels: 매운맛🔥

#32 [나지원] Sprint2
  css/auth.css
  css/main.css
  css/reset.css
  css/variables.css
  images/btn_visibility.png
  images/ic_google.png
  images/ic_kakao.png
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#40 [오혁재] sprint2
  images/Component 2.svg
  images/Component 3.svg
  images/Property 1=Default.svg
  images/Property 1=Variant2.svg
  index.html
  login.css
  login.html
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥

#53 [김지윤] sprint3
  css/components/footer.css
  css/components/header.css
  css/screens/landing-page.css
  css/screens/landing.css
  css/screens/login-signup.css
  css/styles.css
  images/footer/ic_facebook.png
  images/footer/ic_instagram.png
  images/footer/ic_twitter.png
  images/footer/ic_youtube.png
  images/header/Property 1=sm.png
  images/header/Property 1=sm@2x.png
  images/header/Property 1=sm@3x.png
  images/icon/favicon-panda.png
  images/logo/logo-lg.png
  images/logo/logo-md.png
  images/logo/logo-sm.png
  images/logo/logo-typo.png
  images/logo/logo.png
  images/main/Img_home_01.png
  images/main/Img_home_02.png
  images/main/Img_home_03.png
  images/main/Img_home_bottom.png
  images/main/Img_home_top.png
  index.html
  login.html
  signup.html
Labels: 순한맛🐑

#51 [한수진]sprint3
  .DS_Store
  images/.DS_Store
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_top.png
  images/home/bottom-banner-image.png
  images/home/feature1-image.png
  images/home/feature2-image.png
  images/home/feature3-image.png
  images/home/hero-image.png
  images/ic_facebook.png
  images/ic_instagram.png
  images/ic_twitter.png
  images/ic_youtube.png
  images/icons/eye-invisible.svg
  images/icons/eye-visible.svg
  images/login1.png
  images/login2.png
  images/login3.png
  images/login4.png
  images/logo/.DS_Store
  images/logo/favicon.ico
  images/logo/logo.svg
  images/logo/panda-image.png
  images/logopanda1.png
  images/logopanda2x.png
  images/logopanda3x.png
  images/logopandal2x.png
  images/logopandal3x.png
  images/logopandamd.png
  images/logopandas2x.png
  images/mobile_01.png
  images/mobile_02.png
  images/mobile_03.png
  images/mobile_04.png
  images/mobile_05.png
  images/namepanda1.png
  images/namepanda2.png
  images/namepanda3.png
  images/shopping.png
  images/social/facebook-logo.svg
  images/social/google-logo.png
  images/social/instagram-logo.svg
  images/social/kakao-logo.png
  images/social/twitter-logo.svg
  images/social/youtube-logo.svg
  index.html
  login.html
  signin.css
  signlink.css
  signup.html
  style.css
  styles/.DS_Store
  styles/signin.css
  styles/style.css
Labels: 순한맛🐑

#52 [이수지] sprint3
  assets/images/ic-visibility-off.svg
  assets/images/ic-visibility-on.svg
  assets/images/logo-xs.png
  css/auth.css
  css/fonts.css
  css/login.css
  css/main.css
  index.html
  pages/login.html
  pages/signup.html
Labels: 매운맛🔥

#50 [김수영] sprint3
  index.html
  login.html
  signup.html
  style/auth_mobile.css
  style/index.css
  style/index_mobile.css
  style/index_tablet.css
  style/style.css
Labels: 매운맛🔥

#46 [김희진] sprint3
  .github/workflows/delete-merged-branch-config.yml
  css/global.css
  css/home.css
  css/login.css
  css/reset.css
  fonts/ROKAF_Sans_Bold.ttf
  index.html
  login/index.html
  signup/index.html
Labels: 매운맛🔥

#47 [박지민] sprint3
  assets/Img_home_01.png
  assets/Img_home_01.svg
  assets/Img_home_02.png
  assets/Img_home_02.svg
  assets/Img_home_03.png
  assets/Img_home_03.svg
  assets/Img_home_bottom.png
  assets/Img_home_bottom.svg
  assets/Img_home_top.png
  assets/Img_home_top.svg
  assets/btn_visibility_off_24px.png
  assets/btn_visibility_off_24px.svg
  assets/btn_visibility_on_24px.png
  assets/btn_visibility_on_24px.svg
  assets/ic_color_google.png
  assets/ic_color_google.svg
  assets/ic_color_kakaotalk.png
  assets/ic_color_kakaotalk.svg
  assets/ic_facebook.png
  assets/ic_facebook.svg
  assets/ic_instagram.png
  assets/ic_instagram.svg
  assets/ic_twitter.png
  assets/ic_twitter.svg
  assets/ic_youtube.png
  assets/ic_youtube.svg
  assets/logo.png
  assets/logo.svg
  assets/logo_lg.png
  assets/logo_lg.svg
  assets/logo_md.svg
  assets/logo_text.svg
  faq.html
  index.html
  items.html
  login.html
  privacy.html
  signup.html
  styles/login_signin.css
  styles/style.css
  styles/style_mobile.css
  styles/style_tablet.css
Labels: 매운맛🔥

#48 [나지원] Sprint3
  css/auth.css
  css/main.css
  css/reset.css
  images/Img_home_01.png
  images/Img_home_02.png
  images/Img_home_03.png
  images/Img_home_bottom.png
  images/Img_home_bottom.svg
  images/Img_home_top.png
  images/Img_home_top.svg
  images/btn_hidden.svg
  images/btn_visibility.png
  images/favicon.ico
  images/ic_facebook.png
  images/ic_facebook.svg
  images/ic_google.png
  images/ic_google.svg
  images/ic_instagram.png
  images/ic_instagram.svg
  images/ic_kakao.png
  images/ic_kakao.svg
  images/ic_twitter.png
  images/ic_twitter.svg
  images/ic_youtube.png
  images/ic_youtube.svg
  images/panda_logo.png
  images/panda_logo.svg
  images/panda_typo.svg
  index.html
  login.html
  signup.html
Labels: 매운맛🔥

#55 [김태훈] sprint3
  FAQ/index.html
  index.html
  items/index.html
  login/index.html
  privacy/index.html
  signup/index.html
  styles/home.css
  styles/login-signup.css
  styles/variables.css
Labels: 매운맛🔥, 미완성🫠

#56 [정성현] sprint3
  README.md
  images/common/opengraph_w1200.png
  images/login_signup/google.svg
  index.html
  login.html
  signup.html
  styles/common/global.css
  styles/common/reset.css
  styles/common/variable.css
  styles/index.css
  styles/login_signup.css
Labels: 매운맛🔥

#57 [모수진] Sprint3
  desktop.html
  image/btn_visibility.png
  image/social_google.png
  image/social_kakao.png
  login.html
  signup.html
  style/style_color.css
  style/style_desktop.css
  style/style_login.css
  style/style_signup.css
  style_desktop.css
  style_login.css
  style_signup.css
Labels: 미완성🫠
