Repository codeit-bootcamp-frontend/10-Sprint-Mission, pull requests merged in 2024-11, with the labels that each got.

#125 [김희진] sprint10
  next.config.js
  pages/boards/[id].tsx
  pages/boards/components/BestBoardCard.tsx
  pages/boards/components/BestBoards.tsx
  pages/boards/components/BoardCard.module.css
  pages/boards/components/BoardCard.tsx
  pages/boards/components/Boards.module.css
  pages/boards/components/Boards.tsx
  pages/boards/index.tsx
  src/apis/boardTypes.ts
  src/apis/boardsApi.ts
  src/assets/ic_arrow_down.svg
  src/components/Button.tsx
  src/components/GlobalLayout.module.css
  src/components/GlobalLayout.tsx
  src/components/Header.module.css
  src/components/Header.tsx
  src/hooks/useApi.tsx
  src/hooks/useBoards.ts
  styles/globals.css
Labels: 매운맛🔥, 미완성🫠

#128 [나지원] sprint10
  components/addboard/AddBoardForm.module.css
  components/addboard/AddBoardForm.tsx
  components/board/AddCommentForm.module.css
  components/board/AddCommentForm.tsx
  components/board/BoardDetail.module.css
  components/board/BoardDetail.tsx
  components/board/Comment.module.css
  components/board/Comment.tsx
  components/board/Comments.module.css
  components/board/Comments.tsx
  components/board/EditCommentForm.module.css
  components/board/EditCommentForm.tsx
  components/boards/BestBoard.tsx
  components/boards/BestBoards.module.css
  components/boards/BestBoards.tsx
  components/boards/Board.tsx
  components/boards/BoardList.tsx
  components/layout/Container.tsx
  components/ui/AuthorInfo.tsx
  components/ui/Button.tsx
  components/ui/Dropdown.tsx
  components/ui/FileInput.module.css
  components/ui/FileInput.tsx
  components/ui/HeartButton.module.css
  components/ui/HeartButton.tsx
  components/ui/Input.module.css
  components/ui/Input.tsx
  components/ui/Label.module.css
  components/ui/Label.tsx
  components/ui/LikeCount.tsx
  components/ui/SearchBar.tsx
  components/ui/Textarea.module.css
  components/ui/Textarea.tsx
  components/ui/XButton.module.css
  components/ui/XButton.tsx
  constants/url.ts
  contexts/AuthProvider.tsx
  hooks/useObserver.ts
  lib/fetchData.ts
  lib/formatDate.ts
  next.config.js
  pages/_app.tsx
  pages/addboard.tsx
  pages/board/[id].tsx
  pages/boards.tsx
  public/Img_reply_empty.svg
  public/ic_back.svg
  public/ic_kebab.svg
  public/ic_plus.svg
  public/ic_x.svg
  styles/Board.module.css
  types/articleTypes.ts
Labels: 매운맛🔥

#129 [정성현] sprint10
  public/icons/medal.svg
  src/components/pages/boards/BestItems.tsx
  src/components/pages/boards/componnets/BestItem.module.css
  src/components/pages/boards/componnets/BestItem.tsx
  src/hooks/useMedia.ts
  src/hooks/useMediaQuery.ts
  src/hooks/useQuery.ts
  src/pages/_app.tsx
  src/store/MediaContext.tsx
  src/styles/variable.css
Labels: 매운맛🔥, 미완성🫠

#126 [김수영] sprint10
  components/_styled/addboardStyled.tsx
  components/_styled/boardsStyled.tsx
  components/addboard/AddBoard.tsx
  components/addboard/Styled.tsx
  components/api/api.tsx
  components/board/Article.tsx
  components/board/Comment.tsx
  components/board/CommentItem.tsx
  components/board/Styled.tsx
  components/boards/BestPost.tsx
  components/boards/BestPostCard.tsx
  components/boards/PostCard.tsx
  components/boards/PostList.tsx
  next.config.js
  package-lock.json
  package.json
  pages/addboard/index.tsx
  pages/board/[id].tsx
  pages/boards/index.tsx
Labels: 매운맛🔥

#131 [김주동] sprint11
  api/authApi.ts
  components/board/BestArticlesSection.tsx.bak
  components/layout/Header.tsx
  components/layout/Header.tsx.bak
  components/ui/DropdownMenu.tsx.bak
  components/ui/LikeCountDisplay.tsx.bak
  components/ui/SearchBar.tsx.bak
  package-lock.json
  package.json
  pages/auth/AuthStyles.tsx
  pages/auth/components/PasswordInput.tsx
  pages/auth/components/SocialLogin.tsx
  pages/auth/login/index.tsx
  pages/auth/signup/index.tsx
  styles/LayoutStyles.ts
  types/authTypes.ts
Labels: 순한맛🐑

#132 [이수지] sprint11
  api/itemApi.ts
  components/boards/BestArticlesSection.tsx
  components/items/itemPage/CommentThread.tsx
  components/items/itemPage/ItemProfileSection.tsx
  components/layout/Header.tsx
  components/ui/DropdownMenu.tsx
  components/ui/Icon.tsx
  components/ui/LikeCountDisplay.tsx
  components/ui/PaginationBar.tsx
  components/ui/SearchBar.tsx
  declarations.d.ts
  hooks/useImageUpload.ts
  next.config.mjs
  package.json
  pages/addboard/index.tsx
  pages/items/[id].tsx
  pages/login/index.tsx
  pages/signup/index.tsx
  yarn.lock
Labels: 매운맛🔥, 미완성🫠

#134 [정성현] sprint11
  public/icons/eye_close.svg
  public/icons/eye_open.svg
  public/icons/google.svg
  public/icons/kakaotalk.svg
  src/apis/apis.ts
  src/apis/apis.type.ts
  src/components/layout/Header.module.css
  src/components/layout/Header.tsx
  src/components/pages/account/LogInForm.module.css
  src/components/pages/account/LogInForm.tsx
  src/components/pages/account/SignUpForm.module.css
  src/components/pages/account/SignUpForm.tsx
  src/components/pages/account/SocialLogIn.module.css
  src/components/pages/account/SocialLogIn.tsx
  src/components/pages/boards/BestItems.tsx
  src/hooks/useMedia.ts
  src/pages/login.module.css
  src/pages/login.tsx
  src/pages/signup.module.css
  src/pages/signup.tsx
  src/store/MediaContext.tsx
Labels: 매운맛🔥, 미완성🫠

#133 [나지원] sprint11
  components/addboard/AddBoardForm.tsx
  components/auth/AuthForm.module.css
  components/auth/LoginForm.tsx
  components/auth/SignUpForm.tsx
  components/auth/SocialLogin.module.css
  components/auth/SocialLogin.tsx
  components/board/Comments.tsx
  components/board/EditCommentForm.module.css
  components/board/EditCommentForm.tsx
  components/boards/BestBoards.tsx
  components/boards/BoardList.tsx
  components/layout/Header.module.css
  components/layout/Header.tsx
  components/ui/Dropdown.module.css
  components/ui/Dropdown.tsx
  components/ui/FormInput.tsx
  components/ui/Input.module.css
  components/ui/LinkButton.module.css
  components/ui/LinkButton.tsx
  components/ui/Textarea.tsx
  constants/url.ts
  contexts/AuthProvider.tsx
  hooks/useAuth.ts
  lib/fetchData.ts
  package-lock.json
  package.json
  pages/_app.tsx
  pages/board/[id].tsx
  pages/boards.tsx
  pages/index.tsx
  pages/login.tsx
  pages/signup.tsx
  public/Img_home_01.png
  public/Img_home_02.png
  public/Img_home_03.png
  public/Img_home_bottom.svg
  public/Img_home_top.svg
  public/btn_hide.svg
  public/btn_show.svg
  public/ic_facebook.svg
  public/ic_google.svg
  public/ic_instagram.svg
  public/ic_kakao.svg
  public/ic_twitter.svg
  public/ic_youtube.svg
  styles/App.module.css
  styles/Auth.module.css
  styles/Home.module.css
Labels: 매운맛🔥
